language: java
jdk: oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_install:
  - openssl aes-256-cbc -K $encrypted_bccda7cfe1dd_key -iv $encrypted_bccda7cfe1dd_iv -in id_rsa.enc -out id_rsa -d
install: true
script:
  - mvn package -Drelease
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
